baseURL: https://starlitjoy.com # todo: change site url.
title: Starlit Joy # todo: change site name.
defaultContentLanguage: "en"
theme: cosmic
googleAnalytics: "" # todo: set your analytics id.

params:
  subtitle: Astrophotography Gallery # todo: change default subtitle for your website
  author: Joy Paulsen # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        archive: 6
        default: 3
      mobile:
        default: 2
  socials:
    - icon: "far fa-envelope fa-lg"
      url: "mailto:hello@joypauls.dev"
      landing: true
    - icon: "fab fa-github fa-lg"
      url: "https://github.com/joypauls"
      landing: true
    - icon: "fab fa-instagram fa-lg"
      url: "https://www.instagram.com/starlit.joy/"
      landing: true
  homepage: "/" # homepage link, mostly same with menu.main[0]
  callToActionLink: "/gallery/"
  specialPages:
    - gallery
    # - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it"s true.
  disableWelcomePageBackground: true # disables the background image on the homepage
  plausible: "" # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  gallery: ":filename/"

menu:
  main:
    - name: gallery
      url: /gallery/
      weight: 1
    - name: learn
      url: /learn/
      weight: 2
    - name: about
      url: /about/
      weight: 3
